version: "3.9"


services:
  gin:
    image: patrick204nqh/pagoni:latest
    container_name: pagoni-gin
    command: go run main.go
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/backend
      - go_pkg:/go
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: pagoni-postgres
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - $PWD/docker/postgres/init-scripts/:/docker-entrypoint-initdb.d/
      - pagoni_data:/var/lib/postgresql/data
      
  redis:
    image: redis:4.0
    container_name: pagoni-redis
    ports:
      - 6379:6379

  redis-gui:
    image: marian/rebrow:latest
    container_name: pagoni-redis-gui
    ports:
      - 5001:5001

  mailhog:
    image: mailhog/mailhog
    container_name: pagoni-mailhog
    ports:
      - 8025:8025
      - 1025:1025


volumes:
  pagoni_data:
  go_pkg:
